# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5-node
<<<<<<< HEAD
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: sealas
          POSTGRES_DB: sealas
          POSTGRES_PASSWORD: "sealas"
=======
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
>>>>>>> Also add circle-ci tests

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: npm i
      - run: npm run mdlint
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
