# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5-node
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: sealas
          POSTGRES_DB: sealas
          POSTGRES_PASSWORD: "sealas"

    working_directory: ~/sealas
    environment:
      MIX_HOME: /home/circleci/sealas/_mix_ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - sealas-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm i
      - save_cache:
          key: sealas-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run mdlint

      - restore_cache:
          keys:
            - sealas-mix-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - _mix_ci

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
      - run: mix dialyzer
      - save_cache:
          key: sealas-mix-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - _mix_ci
